ingestion:
  - "metadata-ingestion/**/*"

devops:
  - "docker/**/*"
  - ".github/**/*"

product:
  - "datahub-web-react/**/*"
  - "datahub-frontend/**/*"
  - "datahub-graphql-core/**/*"
  - "metadata-io/**/*"

docs:
  - "docs/**/*"

smoke_test:
  - "smoke-test/**/*"
